on:
  # schedule:
  #   - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

env:
  PROJECT_ID: 70  # <== customize this per team/project
  SNAPSHOT_DIR: snapshots  # <== customize where you want .json files to live

jobs:
  export:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
