name: generate projects data

on:
  # schedule:
  #   - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

env:
  PROJECT_ID: 70  # <== customize this per team/project
  SNAPSHOT_DIR: snapshots  # <== customize where you want .json files to live

jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4

      - name: Use GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth status
          gh issue list --repo fleetdm/fleet --limit 5
